### ISSUE TITLE
[Low-priority] When running Charvatia, FreeSO complains about failing to link Monogame, but continues regardless

### ISSUE THREAD

**Issue by jackmawer** [RHY3756547/FreeSO#15]
This is a pretty low priority issue as the game functions correctly after closing the error message, but it is slightly annoying.
On startup, while Charvatia has claimed exclusive access to the Monogame dll in the root directory, FreeSO tries to use it and fails. This results in the following error message:

![Error message reading "Unable to link Monogame"](http://i.imgur.com/PVk25G4.png)

Since the global server will render Charvatia obsolete, this problem will be resolved then. Even so, it would be nice to at least have a flag that suppressed this error.

**Comment by RHY3756547** [comment]
This error appears because FreeSO must dynamically link the correct monogame dll from the Monogame/ folders. Having a monogame dll in the game directory disallows this style of dynamic linking and can break things. This is not a FreeSO bug, and I'm tempted to say it's not even a bug at all since charvatia is purely experimental and will be phased out.

**Comment by jackmawer** [comment]
Indeed, I'd say this can be ignored as it's such a small issue and will be made redundant anyway when Charvatia is phased out.
